#
# Copyright (c) Microsoft. All rights reserved.
#

# CoreGraphics.Drawing.UnitTests.exe
UT_NAME = CoreGraphics.Drawing
UT_FILES := $(filter-out TAEF%,$(wildcard *.cpp))
UT_RESOURCES := data
UT_FRAMEWORKS = CoreGraphics ImageIO CoreText

include ../UT.common.mk
