//******************************************************************************
//
// Copyright (c) 2016 Microsoft Corporation. All rights reserved.
//
// This code is licensed under the MIT License (MIT).
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
//******************************************************************************

#pragma once

#ifndef CORETELEPHONY_IMPEXP
#define CORETELEPHONY_IMPEXP __declspec(dllimport)
#endif

#ifndef CORETELEPHONY_EXPORT
#ifdef __cplusplus
#define CORETELEPHONY_EXPORT CORETELEPHONY_IMPEXP extern "C"
#define CORETELEPHONY_EXPORT_CLASS CORETELEPHONY_IMPEXP
#else
#define CORETELEPHONY_EXPORT CORETELEPHONY_IMPEXP extern
#define CORETELEPHONY_EXPORT_CLASS CORETELEPHONY_IMPEXP
#endif
#endif

#ifndef CORETELEPHONY_EXTERNC_BEGIN
#if defined(__cplusplus)
#define CORETELEPHONY_EXTERNC_BEGIN extern "C" {
#define CORETELEPHONY_EXTERNC_END }
#else
#define CORETELEPHONY_EXTERNC_BEGIN
#define CORETELEPHONY_EXTERNC_END
#endif
#endif
