//******************************************************************************
//
// Copyright (c) 2016 Microsoft Corporation. All rights reserved.
//
// This code is licensed under the MIT License (MIT).
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
//******************************************************************************

#pragma once

#ifndef MOBILECORESERVICES_IMPEXP
#define MOBILECORESERVICES_IMPEXP __declspec(dllimport)
#endif

#ifndef MOBILECORESERVICES_EXPORT
#ifdef __cplusplus
#define MOBILECORESERVICES_EXPORT MOBILECORESERVICES_IMPEXP extern "C"
#define MOBILECORESERVICES_EXPORT_CLASS MOBILECORESERVICES_IMPEXP
#else
#define MOBILECORESERVICES_EXPORT MOBILECORESERVICES_IMPEXP extern
#define MOBILECORESERVICES_EXPORT_CLASS MOBILECORESERVICES_IMPEXP
#endif
#endif

#ifndef MOBILECORESERVICES_EXTERNC_BEGIN
#if defined(__cplusplus)
#define MOBILECORESERVICES_EXTERNC_BEGIN extern "C" {
#define MOBILECORESERVICES_EXTERNC_END }
#else
#define MOBILECORESERVICES_EXTERNC_BEGIN
#define MOBILECORESERVICES_EXTERNC_END
#endif
#endif
