//******************************************************************************
//
// Copyright (c) 2015 Microsoft Corporation. All rights reserved.
//
// This code is licensed under the MIT License (MIT).
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
//******************************************************************************
#ifndef COREBLUETOOTH_IMPEXP
#define COREBLUETOOTH_IMPEXP __declspec(dllimport)
#endif

#ifndef COREBLUETOOTH_EXPORT
#ifdef __cplusplus
#define COREBLUETOOTH_EXPORT COREBLUETOOTH_IMPEXP extern "C"
#define COREBLUETOOTH_EXPORT_CLASS COREBLUETOOTH_IMPEXP
#else
#define COREBLUETOOTH_EXPORT COREBLUETOOTH_IMPEXP extern
#define COREBLUETOOTH_EXPORT_CLASS COREBLUETOOTH_IMPEXP
#endif
#endif
