//******************************************************************************
//
// Copyright (c) 2016 Microsoft Corporation. All rights reserved.
//
// This code is licensed under the MIT License (MIT).
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
//******************************************************************************

#pragma once

#ifndef SAFARISERVICES_IMPEXP
#define SAFARISERVICES_IMPEXP __declspec(dllimport)
#endif

#ifndef SAFARISERVICES_EXPORT
#ifdef __cplusplus
#define SAFARISERVICES_EXPORT SAFARISERVICES_IMPEXP extern "C"
#define SAFARISERVICES_EXPORT_CLASS SAFARISERVICES_IMPEXP
#else
#define SAFARISERVICES_EXPORT SAFARISERVICES_IMPEXP extern
#define SAFARISERVICES_EXPORT_CLASS SAFARISERVICES_IMPEXP
#endif
#endif
