//******************************************************************************
//
// Copyright (c) 2016 Microsoft Corporation. All rights reserved.
//
// This code is licensed under the MIT License (MIT).
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
//******************************************************************************
#pragma once

#ifndef GAMEPLAYKIT_IMPEXP
#define GAMEPLAYKIT_IMPEXP __declspec(dllimport)
#endif

#ifndef GAMEPLAYKIT_EXPORT
#ifdef __cplusplus
#define GAMEPLAYKIT_EXPORT GAMEPLAYKIT_IMPEXP extern "C"
#define GAMEPLAYKIT_EXPORT_CLASS GAMEPLAYKIT_IMPEXP
#else
#define GAMEPLAYKIT_EXPORT GAMEPLAYKIT_IMPEXP extern
#define GAMEPLAYKIT_EXPORT_CLASS GAMEPLAYKIT_IMPEXP
#endif
#endif

#ifndef GAMEPLAYKIT_EXTERNC_BEGIN
#if defined(__cplusplus)
#define GAMEPLAYKIT_EXTERNC_BEGIN extern "C" {
#define GAMEPLAYKIT_EXTERNC_END }
#else
#define GAMEPLAYKIT_EXTERNC_BEGIN
#define GAMEPLAYKIT_EXTERNC_END
#endif
#endif
