//******************************************************************************
//
// Copyright (c) 2015 Microsoft Corporation. All rights reserved.
//
// This code is licensed under the MIT License (MIT).
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
//******************************************************************************

#ifndef __WOCSTDLIB_COMINCLUDES
 #error COMIncludes.h not included prior to COMIncludes_End.h
#elif __WOCSTDLIB_COMINCLUDES == 1
 #undef __WOCSTDLIB_COMINCLUDES
 #undef interface
#elif __WOCSTDLIB_COMINCLUDES == 2
 #undef __WOCSTDLIB_COMINCLUDES
 #define __WOCSTDLIB_COMINCLUDES 1
#elif __WOCSTDLIB_COMINCLUDES == 3
 #undef __WOCSTDLIB_COMINCLUDES
 #define __WOCSTDLIB_COMINCLUDES 2
#elif __WOCSTDLIB_COMINCLUDES == 4
 #undef __WOCSTDLIB_COMINCLUDES
 #define __WOCSTDLIB_COMINCLUDES 3
#elif __WOCSTDLIB_COMINCLUDES == 5
 #undef __WOCSTDLIB_COMINCLUDES
 #define __WOCSTDLIB_COMINCLUDES 4
#elif __WOCSTDLIB_COMINCLUDES == 6
 #undef __WOCSTDLIB_COMINCLUDES
 #define __WOCSTDLIB_COMINCLUDES 5
#elif __WOCSTDLIB_COMINCLUDES == 7
 #undef __WOCSTDLIB_COMINCLUDES
 #define __WOCSTDLIB_COMINCLUDES 6
##elif __WOCSTDLIB_COMINCLUDES == 8
 #undef __WOCSTDLIB_COMINCLUDES
 #define __WOCSTDLIB_COMINCLUDES 7
#elif __WOCSTDLIB_COMINCLUDES == 9
 #undef __WOCSTDLIB_COMINCLUDES
 #define __WOCSTDLIB_COMINCLUDES 8
#else
 #error COMIncludes_End.h __WOCSTDLIB_COMINCLUDES value too high
#endif