//******************************************************************************
//
// Copyright (c) 2016 Microsoft Corporation. All rights reserved.
//
// This code is licensed under the MIT License (MIT).
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
//******************************************************************************

#ifndef COREMOTION_IMPEXP
#define COREMOTION_IMPEXP __declspec(dllimport)
#endif

#ifndef COREMOTION_EXPORT
#ifdef __cplusplus
#define COREMOTION_EXPORT COREMOTION_IMPEXP extern "C"
#define COREMOTION_EXPORT_CLASS COREMOTION_IMPEXP
#else
#define COREMOTION_EXPORT COREMOTION_IMPEXP extern
#define COREMOTION_EXPORT_CLASS COREMOTION_IMPEXP
#endif
#endif

#ifndef COREMOTION_EXTERNC_BEGIN
#if defined(__cplusplus)
#define COREMOTION_EXTERNC_BEGIN extern "C" {
#define COREMOTION_EXTERNC_END }
#else
#define COREMOTION_EXTERNC_BEGIN
#define COREMOTION_EXTERNC_END
#endif
#endif
