//******************************************************************************
//
// Copyright (c) 2016 Microsoft Corporation. All rights reserved.
//
// This code is licensed under the MIT License (MIT).
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
//******************************************************************************
#pragma once

#ifndef MEDIAACCESSIBILITY_IMPEXP
#define MEDIAACCESSIBILITY_IMPEXP __declspec(dllimport)
#endif

#ifndef MEDIAACCESSIBILITY_EXPORT
#ifdef __cplusplus
#define MEDIAACCESSIBILITY_EXPORT MEDIAACCESSIBILITY_IMPEXP extern "C"
#define MEDIAACCESSIBILITY_EXPORT_CLASS MEDIAACCESSIBILITY_IMPEXP
#else
#define MEDIAACCESSIBILITY_EXPORT MEDIAACCESSIBILITY_IMPEXP extern
#define MEDIAACCESSIBILITY_EXPORT_CLASS MEDIAACCESSIBILITY_IMPEXP
#endif
#endif

#ifndef MEDIAACCESSIBILITY_EXTERNC_BEGIN
#if defined(__cplusplus)
#define MEDIAACCESSIBILITY_EXTERNC_BEGIN extern "C" {
#define MEDIAACCESSIBILITY_EXTERNC_END }
#else
#define MEDIAACCESSIBILITY_EXTERNC_BEGIN
#define MEDIAACCESSIBILITY_EXTERNC_END
#endif
#endif
