//******************************************************************************
//
// Copyright (c) 2015 Microsoft Corporation. All rights reserved.
//
// This code is licensed under the MIT License (MIT).
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
//******************************************************************************
#ifndef QUARTZCORE_IMPEXP
#ifdef __QUARTZCORE_INSIDE_BUILD
#define QUARTZCORE_IMPEXP __declspec(dllexport)
#else
#define QUARTZCORE_IMPEXP __declspec(dllimport)
#endif
#endif

#ifndef QUARTZCORE_EXPORT
#ifdef __cplusplus
#define QUARTZCORE_EXPORT QUARTZCORE_IMPEXP extern "C"
#define QUARTZCORE_EXPORT_CLASS QUARTZCORE_IMPEXP
#else
#define QUARTZCORE_EXPORT QUARTZCORE_IMPEXP extern
#define QUARTZCORE_EXPORT_CLASS QUARTZCORE_IMPEXP
#endif
#endif
