// C++ for the Windows Runtime v1.0.170224.5
// Copyright (c) 2017 Microsoft Corporation. All rights reserved.

#pragma once


WINRT_EXPORT namespace winrt {

namespace ABI::Windows::UI::WebUI {

struct ActivatedEventHandler;
struct EnteredBackgroundEventHandler;
struct IActivatedDeferral;
struct IActivatedEventArgsDeferral;
struct IActivatedOperation;
struct IHtmlPrintDocumentSource;
struct IWebUIActivationStatics;
struct IWebUIActivationStatics2;
struct IWebUIBackgroundTaskInstance;
struct IWebUIBackgroundTaskInstanceStatics;
struct IWebUINavigatedDeferral;
struct IWebUINavigatedEventArgs;
struct IWebUINavigatedOperation;
struct LeavingBackgroundEventHandler;
struct NavigatedEventHandler;
struct ResumingEventHandler;
struct SuspendingEventHandler;
struct ActivatedDeferral;
struct ActivatedOperation;
struct EnteredBackgroundEventArgs;
struct HtmlPrintDocumentSource;
struct LeavingBackgroundEventArgs;
struct SuspendingDeferral;
struct SuspendingEventArgs;
struct SuspendingOperation;
struct WebUIAppointmentsProviderAddAppointmentActivatedEventArgs;
struct WebUIAppointmentsProviderRemoveAppointmentActivatedEventArgs;
struct WebUIAppointmentsProviderReplaceAppointmentActivatedEventArgs;
struct WebUIAppointmentsProviderShowAppointmentDetailsActivatedEventArgs;
struct WebUIAppointmentsProviderShowTimeFrameActivatedEventArgs;
struct WebUIBackgroundTaskInstanceRuntimeClass;
struct WebUICachedFileUpdaterActivatedEventArgs;
struct WebUICameraSettingsActivatedEventArgs;
struct WebUIContactCallActivatedEventArgs;
struct WebUIContactMapActivatedEventArgs;
struct WebUIContactMessageActivatedEventArgs;
struct WebUIContactPickerActivatedEventArgs;
struct WebUIContactPostActivatedEventArgs;
struct WebUIContactVideoCallActivatedEventArgs;
struct WebUIDeviceActivatedEventArgs;
struct WebUIDevicePairingActivatedEventArgs;
struct WebUIDialReceiverActivatedEventArgs;
struct WebUIFileActivatedEventArgs;
struct WebUIFileOpenPickerActivatedEventArgs;
struct WebUIFileOpenPickerContinuationEventArgs;
struct WebUIFileSavePickerActivatedEventArgs;
struct WebUIFileSavePickerContinuationEventArgs;
struct WebUIFolderPickerContinuationEventArgs;
struct WebUILaunchActivatedEventArgs;
struct WebUILockScreenActivatedEventArgs;
struct WebUILockScreenCallActivatedEventArgs;
struct WebUINavigatedDeferral;
struct WebUINavigatedEventArgs;
struct WebUINavigatedOperation;
struct WebUIPrint3DWorkflowActivatedEventArgs;
struct WebUIPrintTaskSettingsActivatedEventArgs;
struct WebUIProtocolActivatedEventArgs;
struct WebUIProtocolForResultsActivatedEventArgs;
struct WebUIRestrictedLaunchActivatedEventArgs;
struct WebUISearchActivatedEventArgs;
struct WebUIShareTargetActivatedEventArgs;
struct WebUIToastNotificationActivatedEventArgs;
struct WebUIUserDataAccountProviderActivatedEventArgs;
struct WebUIVoiceCommandActivatedEventArgs;
struct WebUIWalletActionActivatedEventArgs;
struct WebUIWebAccountProviderActivatedEventArgs;
struct WebUIWebAuthenticationBrokerContinuationEventArgs;

}

namespace Windows::UI::WebUI {

struct ActivatedEventHandler;
struct EnteredBackgroundEventHandler;
struct LeavingBackgroundEventHandler;
struct NavigatedEventHandler;
struct ResumingEventHandler;
struct SuspendingEventHandler;
struct IActivatedDeferral;
struct IActivatedEventArgsDeferral;
struct IActivatedOperation;
struct IHtmlPrintDocumentSource;
struct IWebUIActivationStatics;
struct IWebUIActivationStatics2;
struct IWebUIBackgroundTaskInstance;
struct IWebUIBackgroundTaskInstanceStatics;
struct IWebUINavigatedDeferral;
struct IWebUINavigatedEventArgs;
struct IWebUINavigatedOperation;
struct ActivatedDeferral;
struct ActivatedOperation;
struct EnteredBackgroundEventArgs;
struct HtmlPrintDocumentSource;
struct LeavingBackgroundEventArgs;
struct SuspendingDeferral;
struct SuspendingEventArgs;
struct SuspendingOperation;
struct WebUIApplication;
struct WebUIAppointmentsProviderAddAppointmentActivatedEventArgs;
struct WebUIAppointmentsProviderRemoveAppointmentActivatedEventArgs;
struct WebUIAppointmentsProviderReplaceAppointmentActivatedEventArgs;
struct WebUIAppointmentsProviderShowAppointmentDetailsActivatedEventArgs;
struct WebUIAppointmentsProviderShowTimeFrameActivatedEventArgs;
struct WebUIBackgroundTaskInstance;
struct WebUIBackgroundTaskInstanceRuntimeClass;
struct WebUICachedFileUpdaterActivatedEventArgs;
struct WebUICameraSettingsActivatedEventArgs;
struct WebUIContactCallActivatedEventArgs;
struct WebUIContactMapActivatedEventArgs;
struct WebUIContactMessageActivatedEventArgs;
struct WebUIContactPickerActivatedEventArgs;
struct WebUIContactPostActivatedEventArgs;
struct WebUIContactVideoCallActivatedEventArgs;
struct WebUIDeviceActivatedEventArgs;
struct WebUIDevicePairingActivatedEventArgs;
struct WebUIDialReceiverActivatedEventArgs;
struct WebUIFileActivatedEventArgs;
struct WebUIFileOpenPickerActivatedEventArgs;
struct WebUIFileOpenPickerContinuationEventArgs;
struct WebUIFileSavePickerActivatedEventArgs;
struct WebUIFileSavePickerContinuationEventArgs;
struct WebUIFolderPickerContinuationEventArgs;
struct WebUILaunchActivatedEventArgs;
struct WebUILockScreenActivatedEventArgs;
struct WebUILockScreenCallActivatedEventArgs;
struct WebUINavigatedDeferral;
struct WebUINavigatedEventArgs;
struct WebUINavigatedOperation;
struct WebUIPrint3DWorkflowActivatedEventArgs;
struct WebUIPrintTaskSettingsActivatedEventArgs;
struct WebUIProtocolActivatedEventArgs;
struct WebUIProtocolForResultsActivatedEventArgs;
struct WebUIRestrictedLaunchActivatedEventArgs;
struct WebUISearchActivatedEventArgs;
struct WebUIShareTargetActivatedEventArgs;
struct WebUIToastNotificationActivatedEventArgs;
struct WebUIUserDataAccountProviderActivatedEventArgs;
struct WebUIVoiceCommandActivatedEventArgs;
struct WebUIWalletActionActivatedEventArgs;
struct WebUIWebAccountProviderActivatedEventArgs;
struct WebUIWebAuthenticationBrokerContinuationEventArgs;

}

namespace Windows::UI::WebUI {

template <typename T> struct impl_IActivatedDeferral;
template <typename T> struct impl_IActivatedEventArgsDeferral;
template <typename T> struct impl_IActivatedOperation;
template <typename T> struct impl_IHtmlPrintDocumentSource;
template <typename T> struct impl_IWebUIActivationStatics;
template <typename T> struct impl_IWebUIActivationStatics2;
template <typename T> struct impl_IWebUIBackgroundTaskInstance;
template <typename T> struct impl_IWebUIBackgroundTaskInstanceStatics;
template <typename T> struct impl_IWebUINavigatedDeferral;
template <typename T> struct impl_IWebUINavigatedEventArgs;
template <typename T> struct impl_IWebUINavigatedOperation;
template <typename T> struct impl_ActivatedEventHandler;
template <typename T> struct impl_EnteredBackgroundEventHandler;
template <typename T> struct impl_LeavingBackgroundEventHandler;
template <typename T> struct impl_NavigatedEventHandler;
template <typename T> struct impl_ResumingEventHandler;
template <typename T> struct impl_SuspendingEventHandler;

}

namespace Windows::UI::WebUI {

enum class PrintContent
{
    AllPages = 0,
    CurrentPage = 1,
    CustomPageRange = 2,
    CurrentSelection = 3,
};

}

}
