// C++ for the Windows Runtime v1.0.170224.5
// Copyright (c) 2017 Microsoft Corporation. All rights reserved.

#pragma once


WINRT_EXPORT namespace winrt {

namespace ABI::Windows::ApplicationModel::Appointments::DataProvider {

struct IAppointmentCalendarCancelMeetingRequest;
struct IAppointmentCalendarCancelMeetingRequestEventArgs;
struct IAppointmentCalendarCreateOrUpdateAppointmentRequest;
struct IAppointmentCalendarCreateOrUpdateAppointmentRequestEventArgs;
struct IAppointmentCalendarForwardMeetingRequest;
struct IAppointmentCalendarForwardMeetingRequestEventArgs;
struct IAppointmentCalendarProposeNewTimeForMeetingRequest;
struct IAppointmentCalendarProposeNewTimeForMeetingRequestEventArgs;
struct IAppointmentCalendarSyncManagerSyncRequest;
struct IAppointmentCalendarSyncManagerSyncRequestEventArgs;
struct IAppointmentCalendarUpdateMeetingResponseRequest;
struct IAppointmentCalendarUpdateMeetingResponseRequestEventArgs;
struct IAppointmentDataProviderConnection;
struct IAppointmentDataProviderTriggerDetails;
struct AppointmentCalendarCancelMeetingRequest;
struct AppointmentCalendarCancelMeetingRequestEventArgs;
struct AppointmentCalendarCreateOrUpdateAppointmentRequest;
struct AppointmentCalendarCreateOrUpdateAppointmentRequestEventArgs;
struct AppointmentCalendarForwardMeetingRequest;
struct AppointmentCalendarForwardMeetingRequestEventArgs;
struct AppointmentCalendarProposeNewTimeForMeetingRequest;
struct AppointmentCalendarProposeNewTimeForMeetingRequestEventArgs;
struct AppointmentCalendarSyncManagerSyncRequest;
struct AppointmentCalendarSyncManagerSyncRequestEventArgs;
struct AppointmentCalendarUpdateMeetingResponseRequest;
struct AppointmentCalendarUpdateMeetingResponseRequestEventArgs;
struct AppointmentDataProviderConnection;
struct AppointmentDataProviderTriggerDetails;

}

namespace Windows::ApplicationModel::Appointments::DataProvider {

struct IAppointmentCalendarCancelMeetingRequest;
struct IAppointmentCalendarCancelMeetingRequestEventArgs;
struct IAppointmentCalendarCreateOrUpdateAppointmentRequest;
struct IAppointmentCalendarCreateOrUpdateAppointmentRequestEventArgs;
struct IAppointmentCalendarForwardMeetingRequest;
struct IAppointmentCalendarForwardMeetingRequestEventArgs;
struct IAppointmentCalendarProposeNewTimeForMeetingRequest;
struct IAppointmentCalendarProposeNewTimeForMeetingRequestEventArgs;
struct IAppointmentCalendarSyncManagerSyncRequest;
struct IAppointmentCalendarSyncManagerSyncRequestEventArgs;
struct IAppointmentCalendarUpdateMeetingResponseRequest;
struct IAppointmentCalendarUpdateMeetingResponseRequestEventArgs;
struct IAppointmentDataProviderConnection;
struct IAppointmentDataProviderTriggerDetails;
struct AppointmentCalendarCancelMeetingRequest;
struct AppointmentCalendarCancelMeetingRequestEventArgs;
struct AppointmentCalendarCreateOrUpdateAppointmentRequest;
struct AppointmentCalendarCreateOrUpdateAppointmentRequestEventArgs;
struct AppointmentCalendarForwardMeetingRequest;
struct AppointmentCalendarForwardMeetingRequestEventArgs;
struct AppointmentCalendarProposeNewTimeForMeetingRequest;
struct AppointmentCalendarProposeNewTimeForMeetingRequestEventArgs;
struct AppointmentCalendarSyncManagerSyncRequest;
struct AppointmentCalendarSyncManagerSyncRequestEventArgs;
struct AppointmentCalendarUpdateMeetingResponseRequest;
struct AppointmentCalendarUpdateMeetingResponseRequestEventArgs;
struct AppointmentDataProviderConnection;
struct AppointmentDataProviderTriggerDetails;

}

namespace Windows::ApplicationModel::Appointments::DataProvider {

template <typename T> struct impl_IAppointmentCalendarCancelMeetingRequest;
template <typename T> struct impl_IAppointmentCalendarCancelMeetingRequestEventArgs;
template <typename T> struct impl_IAppointmentCalendarCreateOrUpdateAppointmentRequest;
template <typename T> struct impl_IAppointmentCalendarCreateOrUpdateAppointmentRequestEventArgs;
template <typename T> struct impl_IAppointmentCalendarForwardMeetingRequest;
template <typename T> struct impl_IAppointmentCalendarForwardMeetingRequestEventArgs;
template <typename T> struct impl_IAppointmentCalendarProposeNewTimeForMeetingRequest;
template <typename T> struct impl_IAppointmentCalendarProposeNewTimeForMeetingRequestEventArgs;
template <typename T> struct impl_IAppointmentCalendarSyncManagerSyncRequest;
template <typename T> struct impl_IAppointmentCalendarSyncManagerSyncRequestEventArgs;
template <typename T> struct impl_IAppointmentCalendarUpdateMeetingResponseRequest;
template <typename T> struct impl_IAppointmentCalendarUpdateMeetingResponseRequestEventArgs;
template <typename T> struct impl_IAppointmentDataProviderConnection;
template <typename T> struct impl_IAppointmentDataProviderTriggerDetails;

}

}
